export const REMOVE_MANAGER="REMOVE_MANAGER";
export const ADD_CUSTOMER_SUCCESS_MANAGER ="ADD_CUSTOMER_SUCCESS_MANAGER"
export const TOOGLE_LIST="TOOGLE_LIST";
export const ADD_PERMENANT="ADD_PERMENANT";
export const REMOVE_INDIVIDUAL_SELECTED="REMOVE_INDIVIDUAL_SELECTED";
export const GET_LENGTH="GET_LENGTH";
export const CLOSE="CLOSE";
